dbdir: ./cabals
cabal:
  channel: matrix
  nickname: matrix-bot
  key: 1eef9ad64e284691b7c6f6310e39204b5f92765e36102046caaa6a7ff8c02d74
matrix: 
  # On Riot this is under 'Room Settings' => 'Advanced' => 'Room information'.
  room: "!YEFwgTqqXEDd3d:example.com"
  homeserver_url: https://example.com
